name: CI-CD
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
      - run: yarn test:ci

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn bootstrap
      - run: yarn build

  publish-storybook:
    runs-on: ubuntu-latest
    environment: docker-registry
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.flowix.tech
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: yarn && yarn build-storybook
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: .storybook/docker/Dockerfile
          tags: registry.flowix.tech/storybook:latest

  deploy-storybook:
    runs-on: ubuntu-latest
    environment: kubernetes
    needs:
      - publish-storybook
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl rollout restart -n flowix deployment/storybook-components
#      - uses: Azure/k8s-deploy@v4
#        with:
#          action: deploy
#          force: true
#          manifests: |
#            .storybook/kubernetes



#
#
#  publish-packages:
#    runs-on: ubuntu-latest
#    needs:
#      - build
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#
#
